
DROP TABLE IF EXISTS sagas;
CREATE TABLE IF NOT EXISTS sagas (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
);

DROP TABLE IF EXISTS characters;
CREATE TABLE IF NOT EXISTS characters (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	saga_id INTEGER NOT NULL,
	name TEXT NOT NULL,
	events TEXT 
);

DROP TABLE IF EXISTS names;
CREATE TABLE IF NOT EXISTS names (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	character_id INTEGER NOT NULL,
	saga_id INTEGER NOT NULL,	
);

DROP TABLE IF EXISTS relationships;
CREATE TABLE IF NOT EXISTS relationships (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	type TEXT NOT NULL,
	event_id INTEGER NOT NULL,	
	character_a INTEGER NOT NULL,
	character_b INTEGER NOT NULL,
);

DROP TABLE IF EXISTS relationship_types;
CREATE TABLE IF NOT EXISTS relationship_types {
	type TEXT PRIMARY KEY,
	description TEXT NOT NULL
};

DROP TABLE IF EXISTS events;
CREATE TABLE IF NOT EXISTS events {
	id INTERGER PRIMARY KEY AUTOINCREMENT,
	type TEXT NOT NULL,
	order INTEGER DEFAULT 0 NOT NULL,
}; 

DROP TABLE IF EXISTS event_types;
CREATE TABLE IF NOT EXISTS event_types {
	type TEXT PRIMARY KEY,
	description TEXT NOT NULL
};

INSERT INTO event_types (type) 
VALUES 
	("MARRIAGE"),
	("DIVORCE"),
	("BIRTH"),
	("DEATH"),
	("FOSTER");

